In [1]:
from huggingface_hub import hf_hub_download
import os

# Set your target directory
target_dir = "/home/sysadm/Music/HF_MODELS"

# Make sure the directory exists
os.makedirs(target_dir, exist_ok=True)

# Download the model
model_path = hf_hub_download(
    repo_id="TheBloke/Mistral-7B-Instruct-v0.1-GGUF",
    filename="mistral-7b-instruct-v0.1.Q5_K_M.gguf",
    cache_dir=target_dir
)

print(f"✅ Model downloaded to: {model_path}")


mistral-7b-instruct-v0.1.Q5_K_M.gguf:   0%|          | 0.00/5.13G [00:00<?, ?B/s]

✅ Model downloaded to: /home/sysadm/Music/HF_MODELS/models--TheBloke--Mistral-7B-Instruct-v0.1-GGUF/snapshots/731a9fc8f06f5f5e2db8a0cf9d256197eb6e05d1/mistral-7b-instruct-v0.1.Q5_K_M.gguf


In [1]:
from llama_cpp import Llama


model_path = "/home/sysadm/Music/HF_MODELS/models--TheBloke--Mistral-7B-Instruct-v0.1-GGUF/snapshots/731a9fc8f06f5f5e2db8a0cf9d256197eb6e05d1/mistral-7b-instruct-v0.1.Q5_K_M.gguf"

llm = Llama(
    model_path=model_path,
    n_ctx=2048,       
    n_gpu_layers=-1,  
    verbose=True     
)

prompt = "<s>[INST] What is LLM model? [/INST]"


output = llm(prompt, max_tokens=256) 


llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from /home/sysadm/Music/HF_MODELS/models--TheBloke--Mistral-7B-Instruct-v0.1-GGUF/snapshots/731a9fc8f06f5f5e2db8a0cf9d256197eb6e05d1/mistral-7b-instruct-v0.1.Q5_K_M.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.1
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv

llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q5_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
print_info: file format = GGUF V2
print_info: file type   = Q5_K - Medium
print_info: f

In [2]:
print(output["choices"][0]["text"])

 LLM (Language Model) is a type of machine learning model that is designed to process and generate natural language text. It is a type of neural network that is trained on large amounts of text data to learn the patterns and structures of language.

An LLM model can be used for a variety of tasks, such as language translation, sentiment analysis, text classification, and natural language generation. It is often used as a building block for more complex natural language processing (NLP) systems, such as chatbots and virtual assistants.

LLM models are typically trained on large datasets of text, such as books, articles, and conversations. During training, the model analyzes the text data and learns to predict the next word in a sequence based on the previous words. This allows the model to generate new text that is similar in style and content to the training data.

Overall, LLM models are an important tool in the field of NLP and have many practical applications in industries such as h

In [4]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

text = "This movie was amazing!"
inputs = tokenizer(text, return_tensors='pt')
outputs = model(**inputs,output_attentions=True)
predictions = torch.argmax(outputs.logits, dim=1)
print(predictions)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.


tensor([1])


In [5]:
print(predictions)

tensor([1])


In [6]:
attention_weights = outputs.attentions
print(attention_weights)

(tensor([[[[9.5403e-02, 1.6854e-01, 4.8033e-02, 6.6409e-02, 5.4846e-02,
           6.9321e-02, 4.9745e-01],
          [2.2846e-01, 4.6601e-02, 8.1310e-02, 1.5081e-01, 1.1191e-01,
           2.8919e-01, 9.1728e-02],
          [4.8128e-02, 1.0984e-01, 1.2732e-01, 8.6939e-02, 1.3819e-01,
           3.5477e-01, 1.3482e-01],
          [1.3911e-01, 7.0341e-02, 5.7223e-02, 2.4085e-01, 1.1874e-01,
           3.2325e-01, 5.0489e-02],
          [9.4749e-02, 1.4157e-01, 8.9600e-02, 1.3781e-01, 9.4319e-02,
           2.5555e-01, 1.8639e-01],
          [7.9533e-02, 9.0009e-02, 1.1166e-01, 2.0188e-01, 1.1654e-01,
           1.2698e-01, 2.7340e-01],
          [1.5126e-01, 1.7478e-01, 8.6270e-02, 9.3770e-02, 8.5098e-02,
           1.8905e-01, 2.1978e-01]],

         [[9.3999e-01, 1.0529e-02, 7.5040e-03, 1.7286e-02, 4.2372e-03,
           1.0930e-02, 9.5198e-03],
          [9.7691e-03, 1.6643e-02, 1.3480e-01, 6.0848e-02, 6.4655e-01,
           8.7074e-02, 4.4315e-02],
          [4.7846e-02, 1.5563e-02,